# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proctor_pb2 as proctor__pb2


class ProctoringServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterCandidate = channel.unary_unary(
            '/proctor.ProctoringService/RegisterCandidate',
            request_serializer=proctor__pb2.RegisterRequest.SerializeToString,
            response_deserializer=proctor__pb2.RegisterResponse.FromString,
        )
        self.StartSession = channel.unary_unary(
            '/proctor.ProctoringService/StartSession',
            request_serializer=proctor__pb2.SessionRequest.SerializeToString,
            response_deserializer=proctor__pb2.SessionResponse.FromString,
        )
        self.AnalyzeFrame = channel.unary_unary(
            '/proctor.ProctoringService/AnalyzeFrame',
            request_serializer=proctor__pb2.FrameRequest.SerializeToString,
            response_deserializer=proctor__pb2.FrameResponse.FromString,
        )
        self.EndSession = channel.unary_unary(
            '/proctor.ProctoringService/EndSession',
            request_serializer=proctor__pb2.SessionRequest.SerializeToString,
            response_deserializer=proctor__pb2.SessionResponse.FromString,
        )


class ProctoringServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterCandidate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProctoringServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'RegisterCandidate': grpc.unary_unary_rpc_method_handler(
            servicer.RegisterCandidate,
            request_deserializer=proctor__pb2.RegisterRequest.FromString,
            response_serializer=proctor__pb2.RegisterResponse.SerializeToString,
        ),
        'StartSession': grpc.unary_unary_rpc_method_handler(
            servicer.StartSession,
            request_deserializer=proctor__pb2.SessionRequest.FromString,
            response_serializer=proctor__pb2.SessionResponse.SerializeToString,
        ),
        'AnalyzeFrame': grpc.unary_unary_rpc_method_handler(
            servicer.AnalyzeFrame,
            request_deserializer=proctor__pb2.FrameRequest.FromString,
            response_serializer=proctor__pb2.FrameResponse.SerializeToString,
        ),
        'EndSession': grpc.unary_unary_rpc_method_handler(
            servicer.EndSession,
            request_deserializer=proctor__pb2.SessionRequest.FromString,
            response_serializer=proctor__pb2.SessionResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'proctor.ProctoringService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))

 # This class is part of an EXPERIMENTAL API.


class ProctoringService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterCandidate(request,
                          target,
                          options=(),
                          channel_credentials=None,
                          call_credentials=None,
                          insecure=False,
                          compression=None,
                          wait_for_ready=None,
                          timeout=None,
                          metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proctor.ProctoringService/RegisterCandidate',
                                             proctor__pb2.RegisterRequest.SerializeToString,
                                             proctor__pb2.RegisterResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartSession(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proctor.ProctoringService/StartSession',
                                             proctor__pb2.SessionRequest.SerializeToString,
                                             proctor__pb2.SessionResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AnalyzeFrame(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proctor.ProctoringService/AnalyzeFrame',
                                             proctor__pb2.FrameRequest.SerializeToString,
                                             proctor__pb2.FrameResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EndSession(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proctor.ProctoringService/EndSession',
                                             proctor__pb2.SessionRequest.SerializeToString,
                                             proctor__pb2.SessionResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
